// dev

/* const PORT = 81;
const DOMAIN = 'http://counter-offensive'; */

//prod

const PORT = null;
const DOMAIN = "http://counter-offensive";

export const HOST = PORT ? `${DOMAIN}:${PORT}` : DOMAIN;

export const MEDIATOR = {
    EVENTS: {
        SERVER_ERROR: "SERVER_ERROR",
    },
    TRIGGERS: {
        WARNING: "WARNING",
        LOGIN: "LOGIN",
        LOGOUT: "LOGOUT",
        AUTH_ERROR: "AUTH_ERROR",
        ROLE_ERROR: "ROLE_ERROR",
        THROW_TO_GAME: "THROW_TO_GAME",
        THROW_TO_LOBBY: "THROW_TO_LOBBY",
        UPDATE_SCENE: "UPDATE_SCENE",
        UPDATE_TIME: "UPDATE_TIME",
    },
};

export const MAP_SIZE = {
    width: 150,
    height: 120,
};

export const requestDelay = {
    chat: 2000,
    lobby: 300,
    game: 150,
    gamerUpdate: 150,
};

export const entitiesConfig = {
    infantry: {
        speed: 0.004,
        r: 0.35,
        weaponLength: 0.6,
        visiableAngle: 120,
    },

    infantryRGP: {
        speed: 0.0035,
        r: 0.35,
        weaponLength: 0.6,
        visiableAngle: 120,
    },

    middleTank: {
        weaponLength: 1,
        speed: 0.005,
        corpusR: 1,
        towerR: 0,
        rotateSpeed: (Math.PI / 180) * 0.04,
        rotateTowerSpeed: (Math.PI / 180) * 0.04,
        visiableAngle: {
            gunner: 45,
            driver: 60,
        },
    },

    heavyTank: {
        weaponLength: 1,
        speed: 0.004,
        corpusR: 1.2,
        towerR: 0,
        rotateSpeed: (Math.PI / 180) * 0.035,
        rotateTowerSpeed: (Math.PI / 180) * 0.04,
        visiableAngle: {
            gunner: 45,
            driver: 60,
            comander: 180,
        },
    },

    bannerman: {
        speed: 0.002,
        r: 0.35,
        visiableAngle: 120,
    },

    general: {
        speed: 0.06,
    },

    bulletSpeed: 0.1,
};

export const objectConf = {
    stone: {
        r: 1,
    },
    house: {
        width: 6,
        height: 3,
    },
    stump: {
        r: 1,
    },
    bush: {
        r: 1,
    },
    tree: {
        r: 1.5,
    },
    base: {
        r: 2,
        innerColor: "#8BD033",
        outerColor: "#FF0000",
    },
};

export const WINConf = {
    width: 15,
    height: 15,
};

export const walls = [
    [
        { x: -1, y: -1 },
        { x: -1, y: MAP_SIZE.height + 1 },
        { x: 0, y: MAP_SIZE.height + 1 },
        { x: 0, y: -1 },
    ],
    [
        { x: -1, y: -1 },
        { x: -1, y: 0 },
        { x: MAP_SIZE.width, y: 0 },
        { x: MAP_SIZE.width, y: -1 },
    ],
    [
        { x: MAP_SIZE.width, y: -1 },
        { x: MAP_SIZE.width, y: MAP_SIZE.height + 1 },
        { x: MAP_SIZE.width + 1, y: MAP_SIZE.height + 1 },
        { x: MAP_SIZE.width + 1, y: -1 },
    ],
    [
        { x: 0, y: MAP_SIZE.height },
        { x: 0, y: MAP_SIZE.height + 1 },
        { x: MAP_SIZE.width, y: MAP_SIZE.height + 1 },
        { x: MAP_SIZE.width, y: MAP_SIZE.height },
    ],
];

export const staticMap = {
    bushes: [
        { x: 4, y: 28 },
        { x: 2, y: 32 },
        { x: 5, y: 33 },
        { x: 3, y: 43 },
        { x: 6, y: 44 },
        { x: 12, y: 46 },
        { x: 24, y: 46 },
        { x: 6, y: 54 },
        { x: 9, y: 55 },
        { x: 10, y: 98 },
        { x: 11, y: 95 },
        { x: 8, y: 112 },
        { x: 42, y: 2 },
        { x: 45, y: 3 },
        { x: 44, y: 8 },
        { x: 47, y: 13 },
        { x: 60, y: 13 },
        { x: 32, y: 14 },
        { x: 36, y: 22 },
        { x: 37, y: 27 },
        { x: 45, y: 31 },
        { x: 39, y: 32 },
        { x: 28, y: 28 },
        { x: 24, y: 30 },
        { x: 27, y: 37 },
        { x: 51, y: 41 },
        { x: 50, y: 44 },
        { x: 45, y: 43 },
        { x: 48, y: 50 },
        { x: 64, y: 50 },
        { x: 49, y: 59 },
        { x: 52, y: 60 },
        { x: 57, y: 61 },
        { x: 56, y: 64 },
        { x: 56, y: 64 },
        { x: 63, y: 77 },
        { x: 66, y: 78 },
        { x: 65, y: 75 },
        { x: 64, y: 78 },
        { x: 22, y: 68 },
        { x: 21, y: 71 },
        { x: 24, y: 95 },
        { x: 20, y: 100 },
        { x: 32, y: 118 },
        { x: 38, y: 117 },
        { x: 34, y: 111 },
        { x: 24, y: 111 },
        { x: 36, y: 106 },
        { x: 66, y: 26 },
        { x: 62, y: 27 },
        { x: 63, y: 31 },
        { x: 76, y: 22 },
        { x: 79, y: 32 },
        { x: 75, y: 74 },
        { x: 80, y: 77 },
        { x: 73, y: 91 },
        { x: 77, y: 92 },
        { x: 84, y: 14 },
        { x: 81, y: 101 },
        { x: 85, y: 101 },
        { x: 89, y: 101 },
        { x: 80, y: 105 },
        { x: 84, y: 105 },
        { x: 88, y: 105 },
        { x: 81, y: 109 },
        { x: 85, y: 109 },
        { x: 89, y: 109 },
        { x: 80, y: 113 },
        { x: 84, y: 113 },
        { x: 88, y: 113 },
        { x: 94, y: 8 },
        { x: 91, y: 15 },
        { x: 94, y: 23 },
        { x: 97, y: 41 },
        { x: 90, y: 39 },
        { x: 91, y: 57 },
        { x: 95, y: 58 },
        { x: 93, y: 60 },
        { x: 90, y: 65 },
        { x: 92, y: 68 },
        { x: 96, y: 66 },
        { x: 93, y: 73 },
        { x: 92, y: 76 },
        { x: 96, y: 76 },
        { x: 96, y: 100 },
        { x: 95, y: 109 },
        { x: 98, y: 110 },
        { x: 101, y: 25 },
        { x: 117, y: 64 },
        { x: 114, y: 65 },
        { x: 116, y: 70 },
        { x: 117, y: 81 },
        { x: 114, y: 83 },
        { x: 116, y: 85 },
        { x: 114, y: 112 },
        { x: 113, y: 115 },
        { x: 126, y: 8 },
        { x: 121, y: 12 },
        { x: 121, y: 12 },
        { x: 126, y: 31 },
        { x: 125, y: 32 },
        { x: 124, y: 33 },
        { x: 125, y: 49 },
        { x: 130, y: 50 },
        { x: 125, y: 65 },
        { x: 122, y: 67 },
        { x: 124, y: 69 },
        { x: 128, y: 114 },
        { x: 127, y: 117 },
        { x: 135, y: 8 },
        { x: 131, y: 21 },
        { x: 133, y: 41 },
        { x: 136, y: 42 },
        { x: 132, y: 44 },
        { x: 133, y: 49 },
        { x: 138, y: 52 },
        { x: 137, y: 55 },
        { x: 139, y: 79 },
        { x: 138, y: 80 },
        { x: 137, y: 81 },
        { x: 136, y: 86 },
        { x: 137, y: 87 },
        { x: 136, y: 88 },
        { x: 135, y: 95 },
        { x: 138, y: 96 },
        { x: 134, y: 98 },
        { x: 132, y: 116 },
        { x: 141, y: 5 },
        { x: 148, y: 6 },
        { x: 144, y: 20 },
        { x: 143, y: 22 },
        { x: 146, y: 22 },
        { x: 141, y: 55 },
        { x: 146, y: 66 },
        { x: 142, y: 69 },
        { x: 146, y: 70 },
    ],
    trees: [
        { x: 12, y: 79 },
        { x: 35, y: 87 },
        { x: 31, y: 109 },
        { x: 48, y: 29 },
        { x: 41, y: 76 },
        { x: 44, y: 79 },
        { x: 42, y: 110 },
        { x: 53, y: 79 },
        { x: 56, y: 99 },
        { x: 69, y: 51 },
        { x: 72, y: 7 },
        { x: 76, y: 59 },
        { x: 72, y: 99 },
        { x: 87, y: 5 },
        { x: 82, y: 36 },
        { x: 82, y: 45 },
        { x: 82, y: 45 },
        { x: 98, y: 31 },
        { x: 98, y: 63 },
        { x: 96, y: 117 },
        { x: 103, y: 67 },
        { x: 116, y: 10 },
        { x: 118, y: 21 },
        { x: 124, y: 14 },
        { x: 124, y: 24 },
        { x: 130, y: 7 },
        { x: 136, y: 15 },
        { x: 135, y: 21 },
    ],
    road: [{ x: 108, y: 0, sizeX: 3, sizeY: 120 }],
    crossyRoad: [
        {
            x: 16,
            y: 18,
            sizeX: 2,
            sizeY: 10,
            angle: Math.PI / 2,
        },
        {
            x: 18,
            y: 24,
            sizeX: 14,
            sizeY: 2,
            angle: 0,
        },
        {
            x: 32,
            y: 26,
            sizeX: 2,
            sizeY: 62,
            angle: Math.PI / 2,
        },
        {
            x: 18,
            y: 64,
            sizeX: 14,
            sizeY: 2,
            angle: 0,
        },
        {
            x: 14,
            y: 66,
            sizeX: 2,
            sizeY: 6,
            angle: Math.PI / 2,
        },
        {
            x: 18,
            y: 84,
            sizeX: 14,
            sizeY: 2,
            angle: 0,
        },
        {
            x: 16,
            y: 86,
            sizeX: 2,
            sizeY: 16,
            angle: Math.PI / 2,
        },
        {
            x: 18,
            y: 96,
            sizeX: 6,
            sizeY: 2,
            angle: 0,
        },
        {
            x: 24,
            y: 98,
            sizeX: 2,
            sizeY: 2,
            angle: Math.PI / 2,
        },
        {
            x: 34,
            y: 88,
            sizeX: 74,
            sizeY: 2,
            angle: 0,
        },
        {
            x: 60,
            y: 90,
            sizeX: 2,
            sizeY: 8,
            angle: Math.PI / 2,
        },
        {
            x: 62,
            y: 98,
            sizeX: 4,
            sizeY: 2,
            angle: 0,
        },
        {
            x: 66,
            y: 100,
            sizeX: 2,
            sizeY: 4,
            angle: Math.PI / 2,
        },
        {
            x: 16,
            y: 62,
            sizeX: 2,
            sizeY: 2,
            angle: Math.PI / 2,
        },
        {
            x: 72,
            y: 54,
            sizeX: 2,
            sizeY: 34,
            angle: Math.PI / 2,
        },
        {
            x: 74,
            y: 68,
            sizeX: 2,
            sizeY: 2,
            angle: 0,
        },
        {
            x: 74,
            y: 78,
            sizeX: 34,
            sizeY: 2,
            angle: 0,
        },
        {
            x: 34,
            y: 52,
            sizeX: 74,
            sizeY: 2,
            angle: 0,
        },
        {
            x: 54,
            y: 82,
            sizeX: 2,
            sizeY: 6,
            angle: Math.PI / 2,
        },
        {
            x: 40,
            y: 80,
            sizeX: 14,
            sizeY: 2,
            angle: 0,
        },
        {
            x: 40,
            y: 70,
            sizeX: 8,
            sizeY: 2,
            angle: 0,
        },
        {
            x: 48,
            y: 72,
            sizeX: 2,
            sizeY: 8,
            angle: Math.PI / 2,
        },
        {
            x: 38,
            y: 60,
            sizeX: 2,
            sizeY: 20,
            angle: Math.PI / 2,
        },
        {
            x: 42,
            y: 54,
            sizeX: 2,
            sizeY: 4,
            angle: Math.PI / 2,
        },
        {
            x: 40,
            y: 58,
            sizeX: 2,
            sizeY: 2,
            angle: 0,
        },
        {
            x: 66,
            y: 48,
            sizeX: 2,
            sizeY: 4,
            angle: Math.PI / 2,
        },
        {
            x: 84,
            y: 48,
            sizeX: 2,
            sizeY: 4,
            angle: Math.PI / 2,
        },
        {
            x: 68,
            y: 46,
            sizeX: 16,
            sizeY: 2,
            angle: 0,
        },
        {
            x: 18,
            y: 16,
            sizeX: 90,
            sizeY: 2,
            angle: 0,
        },
        {
            x: 40,
            y: 8,
            sizeX: 2,
            sizeY: 8,
            angle: Math.PI / 2,
        },
        {
            x: 48,
            y: 18,
            sizeX: 2,
            sizeY: 2,
            angle: Math.PI / 2,
        },
        {
            x: 76,
            y: 10,
            sizeX: 2,
            sizeY: 6,
            angle: Math.PI / 2,
        },
        {
            x: 78,
            y: 18,
            sizeX: 2,
            sizeY: 6,
            angle: Math.PI / 2,
        },
        {
            x: 110,
            y: 16,
            sizeX: 40,
            sizeY: 2,
            angle: 0,
        },
        {
            x: 110,
            y: 44,
            sizeX: 18,
            sizeY: 2,
            angle: 0,
        },
        {
            x: 126,
            y: 40,
            sizeX: 2,
            sizeY: 2,
            angle: 0,
        },
        {
            x: 128,
            y: 38,
            sizeX: 2,
            sizeY: 6,
            angle: Math.PI / 2,
        },
        {
            x: 130,
            y: 36,
            sizeX: 8,
            sizeY: 2,
            angle: 0,
        },
        {
            x: 110,
            y: 52,
            sizeX: 18,
            sizeY: 2,
            angle: 0,
        },
        {
            x: 128,
            y: 54,
            sizeX: 2,
            sizeY: 6,
            angle: Math.PI / 2,
        },
        {
            x: 110,
            y: 76,
            sizeX: 32,
            sizeY: 2,
            angle: 0,
        },
        {
            x: 128,
            y: 78,
            sizeX: 2,
            sizeY: 2,
            angle: Math.PI / 2,
        },
        {
            x: 142,
            y: 78,
            sizeX: 2,
            sizeY: 2,
            angle: Math.PI / 2,
        },
        {
            x: 110,
            y: 104,
            sizeX: 26,
            sizeY: 2,
            angle: 0,
        },
        {
            x: 140,
            y: 102,
            sizeX: 10,
            sizeY: 2,
            angle: 0,
        },
        {
            x: 138,
            y: 110,
            sizeX: 2,
            sizeY: 2,
            angle: 0,
        },
        {
            x: 120,
            y: 106,
            sizeX: 2,
            sizeY: 2,
            angle: Math.PI / 2,
        },
        {
            x: 122,
            y: 102,
            sizeX: 2,
            sizeY: 2,
            angle: Math.PI / 2,
        },
        {
            x: 138,
            y: 100,
            sizeX: 2,
            sizeY: 2,
            angle: Math.PI / 2,
        },
        {
            x: 136,
            y: 106,
            sizeX: 2,
            sizeY: 4,
            angle: Math.PI / 2,
        },
    ],
    crossyRoadTurnCont: [
        { x: 42, y: 52, angle: 0 },
        { x: 60, y: 88, angle: 0 },
        { x: 48, y: 16, angle: 0 },
        { x: 78, y: 16, angle: 0 },
        { x: 72, y: 52, angle: 0 },
        { x: 120, y: 104, angle: 0 },
        { x: 136, y: 104, angle: 0 },
        { x: 128, y: 76, angle: 0 },

        { x: 16, y: 96, angle: Math.PI / 2 },
        { x: 16, y: 24, angle: Math.PI / 2 },
        { x: 38, y: 70, angle: Math.PI / 2 },
        { x: 32, y: 46, angle: Math.PI / 2 },
        { x: 32, y: 52, angle: Math.PI / 2 },
        { x: 66, y: 46, angle: Math.PI / 2 },
        { x: 72, y: 68, angle: Math.PI / 2 },
        { x: 72, y: 78, angle: Math.PI / 2 },
        { x: 138, y: 102, angle: Math.PI / 2 },

        { x: 16, y: 64, angle: Math.PI },
        { x: 40, y: 16, angle: Math.PI },
        { x: 48, y: 80, angle: Math.PI },
        { x: 54, y: 88, angle: Math.PI },
        { x: 72, y: 88, angle: Math.PI },
        { x: 84, y: 52, angle: Math.PI },
        { x: 76, y: 16, angle: Math.PI },
        { x: 66, y: 52, angle: Math.PI },
        { x: 134, y: 36, angle: Math.PI },
        { x: 122, y: 104, angle: Math.PI },

        { x: 32, y: 64, angle: (3 * Math.PI) / 2 },
        { x: 32, y: 84, angle: (3 * Math.PI) / 2 },
        { x: 128, y: 40, angle: (3 * Math.PI) / 2 },
    ],
    crossyRoadTurn: [
        { x: 32, y: 24, angle: 0 },
        { x: 24, y: 96, angle: 0 },
        { x: 48, y: 70, angle: 0 },
        { x: 54, y: 80, angle: 0 },
        { x: 66, y: 98, angle: 0 },
        { x: 84, y: 46, angle: 0 },
        { x: 142, y: 76, angle: 0 },
        { x: 128, y: 52, angle: 0 },

        { x: 16, y: 102, angle: Math.PI / 2 },
        { x: 42, y: 58, angle: Math.PI / 2 },
        { x: 78, y: 24, angle: Math.PI / 2 },
        { x: 128, y: 44, angle: Math.PI / 2 },
        { x: 138, y: 104, angle: Math.PI / 2 },

        { x: 32, y: 88, angle: Math.PI },
        { x: 38, y: 80, angle: Math.PI },
        { x: 60, y: 98, angle: Math.PI },
        { x: 136, y: 110, angle: Math.PI },

        { x: 14, y: 64, angle: (3 * Math.PI) / 2 },
        { x: 16, y: 16, angle: (3 * Math.PI) / 2 },
        { x: 16, y: 84, angle: (3 * Math.PI) / 2 },
        { x: 38, y: 58, angle: (3 * Math.PI) / 2 },
        { x: 76, y: 8, angle: (3 * Math.PI) / 2 },
        { x: 128, y: 36, angle: (3 * Math.PI) / 2 },
    ],
    crossyRoadEnd: [
        { x: 14, y: 102, angle: 0 },
        { x: 76, y: 24, angle: 0 },
        { x: 124, y: 40, angle: 0 },

        { x: 16, y: 60, angle: Math.PI / 2 },
        { x: 40, y: 6, angle: Math.PI / 2 },
        { x: 66, y: 44, angle: Math.PI / 2 },
        { x: 122, y: 100, angle: Math.PI / 2 },
        { x: 138, y: 98, angle: Math.PI / 2 },
        { x: 134, y: 34, angle: Math.PI / 2 },

        { x: 34, y: 46, angle: Math.PI },
        { x: 34, y: 46, angle: Math.PI },
        { x: 78, y: 8, angle: Math.PI },
        { x: 76, y: 68, angle: Math.PI },
        { x: 140, y: 110, angle: Math.PI },
        { x: 138, y: 36, angle: Math.PI },

        { x: 16, y: 28, angle: (3 * Math.PI) / 2 },
        { x: 14, y: 72, angle: (3 * Math.PI) / 2 },
        { x: 24, y: 100, angle: (3 * Math.PI) / 2 },
        { x: 48, y: 20, angle: (3 * Math.PI) / 2 },
        { x: 66, y: 104, angle: (3 * Math.PI) / 2 },
        { x: 128, y: 60, angle: (3 * Math.PI) / 2 },
        { x: 128, y: 80, angle: (3 * Math.PI) / 2 },
        { x: 142, y: 80, angle: (3 * Math.PI) / 2 },
        { x: 120, y: 108, angle: (3 * Math.PI) / 2 },
    ],
};
