CREATE TABLE IF NOT EXISTS `game` (
  `id` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `hashUnits` VARCHAR(100) NOT NULL DEFAULT "",
  `hashScene` VARCHAR(100) NOT NULL DEFAULT "",
  `hashBullets` VARCHAR(100) NOT NULL DEFAULT "",
  `hashLobby` VARCHAR(100) NOT NULL DEFAULT "",
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `users` ( 
  `id` MEDIUMINT NOT NULL AUTO_INCREMENT, 
  `login` VARCHAR(20) NOT NULL DEFAULT "", 
  `password` VARCHAR(100) NOT NULL DEFAULT "", 
  `token` VARCHAR(100) NOT NULL DEFAULT "", 
  `tokenLastUse` DATETIME NOT NULL DEFAULT "2000-10-01 00:00:00",
  `timeCreate` DATETIME NOT NULL DEFAULT "2000-10-01 00:00:00", 
  `photo` VARCHAR(100) NOT NULL DEFAULT "default.jpg",
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `gamers` (
  `id` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `user_id` MEDIUMINT NOT NULL DEFAULT -1,
  `person_id` MEDIUMINT NOT NULL DEFAULT -1,
  `experience` INT NOT NULL DEFAULT 0,
  `hp` INT NOT NULL DEFAULT 0,
  `money` INT NOT NULL DEFAULT 0,
  `x` FLOAT NULL DEFAULT NULL,
  `y` FLOAT NULL DEFAULT NULL,
  `angle` FLOAT NULL DEFAULT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT "",
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `persons` (
  `id` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL DEFAULT "Пехотинец",
  `hp` INT NOT NULL DEFAULT 0,
  `image` VARCHAR(100) NOT NULL DEFAULT "standartPerson.jpg",
  `reloadSpeed` FLOAT NOT NULL DEFAULT 1,
  `movementSpeed` FLOAT NOT NULL DEFAULT 1,
  `rotateSpeed` FLOAT NOT NULL DEFAULT 1,
  `level` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `ranks` (
  `id` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL DEFAULT "Медный ранг",
  `experience` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `games` ( 
  `id` MEDIUMINT NOT NULL AUTO_INCREMENT, 
  `users` VARCHAR(100) NOT NULL DEFAULT "[]", 
  `usersCount` INT NOT NULL DEFAULT 0, 
  `startTime` DATETIME NOT NULL DEFAULT "2000-10-01 00:00:00", 
  `endTime` DATETIME NOT NULL DEFAULT "2000-10-01 00:00:00", 
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `messages` (
  `id` MEDIUMINT NOT NULL AUTO_INCREMENT, 
  `userId` MEDIUMINT NOT NULL DEFAULT -1,
  `text` VARCHAR(200) NOT NULL DEFAULT "",
  `sendTime` DATETIME NOT NULL DEFAULT "2000-10-01 00:00:00",
  PRIMARY KEY (`id`)
);